name: check_updates
on:
  schedule:
    # Check daily
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set current date as env variable
        run: |
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
          echo "PR_BRANCH=dep-update-$NOW" >> $GITHUB_ENV

      - name: Check update
        run: ./scripts/admin.sh update_version
      - name: Check for changes
        run: |
          git add -A . ||:

          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes detected"
            exit 0
          fi
          echo "Changes detected. Raising PR"

          git config --global user.email "info@thin-edge.io"
          git config --global user.name "Versioneer"
          git checkout -b "$PR_BRANCH"
          git commit -am "Update version"
          git push --set-upstream origin "$PR_BRANCH"
      - name: create pull request
        run: gh pr create -H "$PR_BRANCH" --title "Update version" --body "Update version"
